services:
    php-apache:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "${SERVER_PORT:-80}:80"
        volumes:
            - ./www:/var/www/html
            - ./configs/php/php.ini:/usr/local/etc/php/php.ini
            - ./configs/apache/vhost.conf:/etc/apache2/sites-available.vhost.conf
            - ./configs/php/mods/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./logs/apache2:/var/log/apache2
            - ./logs/php:/var/log/php
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=exemple.site}
        restart: always
        user: "${UID:-1000}:${GID:-1000}"
        extra_hosts:
            -  "host.docker.internal:host-gateway"
        env_file:
            - ./.env
    db:
        image: mysql:5.7
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-opencart}
            MYSQL_USER: ${MYSQL_USER:-opencart}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-opencart}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
        volumes:
          - ./mysql_data:/var/lib/mysql
          - ./.dockerfile/images/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_INIDB_SKIP_TZINFO: "yes"
            UPLOAD_LIMIT: 100000000
volumes:
  mysql_data:
  logs:


